apiVersion: apps/v1
kind: Deployment
metadata:
  name: admission-webhooks
  namespace: default
spec:
  selector:
    matchLabels:
      app: admission-webhooks
  template:
    metadata:
      labels:
        app: admission-webhooks
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: admission-webhooks
          image: bluebrown/admission-webhooks-example
          imagePullPolicy: Always
          ports:
            - containerPort: 8443
              name: https
            - containerPort: 8080
              name: metrics
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: "100m"
              memory: "128Mi"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          volumeMounts:
            - mountPath: /certs
              name: certs
              readOnly: true
      volumes:
        - name: certs
          secret:
            secretName: admission-webhooks
