apiVersion: v1
kind: Service
metadata:
  name: admission-webhooks
  namespace: sandbox
spec:
  selector:
    app: admission-webhooks
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    - name: metrics
      port: 8080
      targetPort: metrics
      protocol: TCP
