apiVersion: v1
kind: Service
metadata:
  name: admission-webhook
  namespace: example
spec:
  selector:
    app: admission-webhook
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
