apiVersion: batch/v1
kind: Job
metadata:
  name: webhooks-cert-create
spec:
  ttlSecondsAfterFinished: 120
  template:
    spec:
      restartPolicy: Never
      serviceAccount: webhooks-certgen
      securityContext:
        runAsNonRoot: true
        fsGroup: 2000
        runAsUser: 2000
      containers:
        - name: create
          image: registry.k8s.io/ingress-nginx/kube-webhook-certgen:v20220916-gd32f8c343
          args:
            - create
            - --host=admission-webhooks.$(POD_NAMESPACE).svc
            - --namespace=$(POD_NAMESPACE)
            - --secret-name=admission-webhooks
            - --key-name=tls.key
            - --cert-name=tls.crt
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            requests:
              memory: 16Mi
              cpu: 25m
            limits:
              memory: 128Mi
              cpu: 100m
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
